export const countries = [
    { value: "AF", label: "Afghanistan (افغانستان)", flag: "AF" },
    { value: "AL", label: "Albania (Shqipëri)", flag: "AL" },
    { value: "DZ", label: "Algeria (الجزائر)", flag: "DZ" },
    { value: "AR", label: "Argentina (Argentina)", flag: "AR" },
    { value: "AU", label: "Australia (Australia)", flag: "AU" },
    { value: "AT", label: "Austria (Österreich)", flag: "AT" },
    { value: "AZ", label: "Azerbaijan (Azərbaycan)", flag: "AZ" },
    { value: "BH", label: "Bahrain (البحرين)", flag: "BH" },
    { value: "BD", label: "Bangladesh (বাংলাদেশ)", flag: "BD" },
    { value: "BY", label: "Belarus (Беларусь)", flag: "BY" },
    { value: "BE", label: "Belgium (België)", flag: "BE" },
    { value: "BZ", label: "Belize (Belize)", flag: "BZ" },
    { value: "BJ", label: "Benin (Bénin)", flag: "BJ" },
    { value: "BT", label: "Bhutan (འབྲུག)", flag: "BT" },
    { value: "BO", label: "Bolivia (Bolivia)", flag: "BO" },
    { value: "BR", label: "Brazil (Brasil)", flag: "BR" },
    { value: "BN", label: "Brunei (بروني)", flag: "BN" },
    { value: "BG", label: "Bulgaria (България)", flag: "BG" },
    { value: "BF", label: "Burkina Faso (Burkina Faso)", flag: "BF" },
    { value: "BI", label: "Burundi (Burundi)", flag: "BI" },
    { value: "KH", label: "Cambodia (កម្ពុជា)", flag: "KH" },
    { value: "CM", label: "Cameroon (Cameroun)", flag: "CM" },
    { value: "CA", label: "Canada (Canada)", flag: "CA" },
    { value: "CV", label: "Cape Verde (Cabo Verde)", flag: "CV" },
    { value: "CF", label: "Central African Republic (République centrafricaine)", flag: "CF" },
    { value: "TD", label: "Chad (تشاد)", flag: "TD" },
    { value: "CL", label: "Chile (Chile)", flag: "CL" },
    { value: "CN", label: "China (中国)", flag: "CN" },
    { value: "CO", label: "Colombia (Colombia)", flag: "CO" },
    { value: "KM", label: "Comoros (Komori)", flag: "KM" },
    { value: "CG", label: "Congo (République du Congo)", flag: "CG" },
    { value: "CD", label: "Congo (Democratic Republic)", flag: "CD" },
    { value: "CR", label: "Costa Rica (Costa Rica)", flag: "CR" },
    { value: "CI", label: "Côte d'Ivoire (Côte d'Ivoire)", flag: "CI" },
    { value: "HR", label: "Croatia (Hrvatska)", flag: "HR" },
    { value: "CU", label: "Cuba (Cuba)", flag: "CU" },
    { value: "CY", label: "Cyprus (Κύπρος)", flag: "CY" },
    { value: "CZ", label: "Czech Republic (Česko)", flag: "CZ" },
    { value: "DK", label: "Denmark (Danmark)", flag: "DK" },
    { value: "DJ", label: "Djibouti (Djibouti)", flag: "DJ" },
    { value: "DM", label: "Dominica (Dominica)", flag: "DM" },
    { value: "DO", label: "Dominican Republic (República Dominicana)", flag: "DO" },
    { value: "EC", label: "Ecuador (Ecuador)", flag: "EC" },
    { value: "EG", label: "Egypt (مصر)", flag: "EG" },
    { value: "SV", label: "El Salvador (El Salvador)", flag: "SV" },
    { value: "GQ", label: "Equatorial Guinea (Guinea Ecuatorial)", flag: "GQ" },
    { value: "ER", label: "Eritrea (Eritrea)", flag: "ER" },
    { value: "EE", label: "Estonia (Eesti)", flag: "EE" },
    { value: "ET", label: "Ethiopia (Ethiopia)", flag: "ET" },
    { value: "FJ", label: "Fiji (Fiji)", flag: "FJ" },
    { value: "FI", label: "Finland (Suomi)", flag: "FI" },
    { value: "FR", label: "France (France)", flag: "FR" },
    { value: "GA", label: "Gabon (Gabon)", flag: "GA" },
    { value: "GM", label: "Gambia (Gambia)", flag: "GM" },
    { value: "GE", label: "Georgia (საქართველო)", flag: "GE" },
    { value: "DE", label: "Germany (Deutschland)", flag: "DE" },
    { value: "GH", label: "Ghana (Ghana)", flag: "GH" },
    { value: "GR", label: "Greece (Ελλάδα)", flag: "GR" },
    { value: "GT", label: "Guatemala (Guatemala)", flag: "GT" },
    { value: "GN", label: "Guinea (Guinée)", flag: "GN" },
    { value: "GW", label: "Guinea-Bissau (Guiné-Bissau)", flag: "GW" },
    { value: "GY", label: "Guyana (Guyana)", flag: "GY" },
    { value: "HT", label: "Haiti (Haïti)", flag: "HT" },
    { value: "HN", label: "Honduras (Honduras)", flag: "HN" },
    { value: "HU", label: "Hungary (Magyarország)", flag: "HU" },
    { value: "IS", label: "Iceland (Ísland)", flag: "IS" },
    { value: "IN", label: "India (भारत)", flag: "IN" },
    { value: "ID", label: "Indonesia (Indonesia)", flag: "ID" },
    { value: "IR", label: "Iran (ایران)", flag: "IR" },
    { value: "IQ", label: "Iraq (العراق)", flag: "IQ" },
    { value: "IE", label: "Ireland (Éire)", flag: "IE" },
    { value: "IL", label: "Israel (ישראל)", flag: "IL" },
    { value: "IT", label: "Italy (Italia)", flag: "IT" },
    { value: "JM", label: "Jamaica (Jamaica)", flag: "JM" },
    { value: "JP", label: "Japan (日本)", flag: "JP" },
    { value: "JO", label: "Jordan (الأردن)", flag: "JO" },
    { value: "KZ", label: "Kazakhstan (Қазақстан)", flag: "KZ" },
    { value: "KE", label: "Kenya (Kenya)", flag: "KE" },
    { value: "KI", label: "Kiribati (Kiribati)", flag: "KI" },
    { value: "KP", label: "North Korea (북한)", flag: "KP" },
    { value: "KR", label: "South Korea (대한민국)", flag: "KR" },
    { value: "KW", label: "Kuwait (الكويت)", flag: "KW" },
    { value: "KG", label: "Kyrgyzstan (Кыргызстан)", flag: "KG" },
    { value: "LA", label: "Laos (ລາວ)", flag: "LA" },
    { value: "LV", label: "Latvia (Latvija)", flag: "LV" },
    { value: "LB", label: "Lebanon (لبنان)", flag: "LB" },
    { value: "LS", label: "Lesotho (Lesotho)", flag: "LS" },
    { value: "LR", label: "Liberia (Liberia)", flag: "LR" },
    { value: "LY", label: "Libya (ليبيا)", flag: "LY" },
    { value: "LI", label: "Liechtenstein (Liechtenstein)", flag: "LI" },
    { value: "LT", label: "Lithuania (Lietuva)", flag: "LT" },
    { value: "LU", label: "Luxembourg (Luxembourg)", flag: "LU" },
    { value: "MG", label: "Madagascar (Madagasikara)", flag: "MG" },
    { value: "MW", label: "Malawi (Malawi)", flag: "MW" },
    { value: "MY", label: "Malaysia (Malaysia)", flag: "MY" },
    { value: "MV", label: "Maldives (Maldives)", flag: "MV" },
    { value: "ML", label: "Mali (Mali)", flag: "ML" },
    { value: "MT", label: "Malta (Malta)", flag: "MT" },
    { value: "MH", label: "Marshall Islands (Marshall Islands)", flag: "MH" },
    { value: "MR", label: "Mauritania (موريتانيا)", flag: "MR" },
    { value: "MU", label: "Mauritius (Mauritius)", flag: "MU" },
    { value: "MX", label: "Mexico (México)", flag: "MX" },
    { value: "FM", label: "Micronesia (Micronesia)", flag: "FM" },
    { value: "MD", label: "Moldova (Republica Moldova)", flag: "MD" },
    { value: "MC", label: "Monaco (Monaco)", flag: "MC" },
    { value: "MN", label: "Mongolia (Монгол)", flag: "MN" },
    { value: "ME", label: "Montenegro (Crna Gora)", flag: "ME" },
    { value: "MA", label: "Morocco (المغرب)", flag: "MA" },
    { value: "MZ", label: "Mozambique (Moçambique)", flag: "MZ" },
    { value: "MM", label: "Myanmar (Burma) (မြန်မာ)", flag: "MM" },
    { value: "NA", label: "Namibia (Namibia)", flag: "NA" },
    { value: "NR", label: "Nauru (Nauru)", flag: "NR" },
    { value: "NP", label: "Nepal (नेपाल)", flag: "NP" },
    { value: "NL", label: "Netherlands (Nederland)", flag: "NL" },
    { value: "NZ", label: "New Zealand (New Zealand)", flag: "NZ" },
    { value: "NI", label: "Nicaragua (Nicaragua)", flag: "NI" },
    { value: "NE", label: "Niger (Niger)", flag: "NE" },
    { value: "NG", label: "Nigeria (Nigeria)", flag: "NG" },
    { value: "NO", label: "Norway (Norge)", flag: "NO" },
    { value: "OM", label: "Oman (عمان)", flag: "OM" },
    { value: "PK", label: "Pakistan (پاکستان)", flag: "PK" },
    { value: "PW", label: "Palau (Palau)", flag: "PW" },
    { value: "PA", label: "Panama (Panamá)", flag: "PA" },
    { value: "PG", label: "Papua New Guinea (Papua New Guinea)", flag: "PG" },
    { value: "PY", label: "Paraguay (Paraguay)", flag: "PY" },
    { value: "PE", label: "Peru (Perú)", flag: "PE" },
    { value: "PH", label: "Philippines (Pilipinas)", flag: "PH" },
    { value: "PL", label: "Poland (Polska)", flag: "PL" },
    { value: "PT", label: "Portugal (Portugal)", flag: "PT" },
    { value: "QA", label: "Qatar (قطر)", flag: "QA" },
    { value: "RO", label: "Romania (România)", flag: "RO" },
    { value: "RU", label: "Russia (Россия)", flag: "RU" },
    { value: "RW", label: "Rwanda (Rwanda)", flag: "RW" },
    { value: "KN", label: "Saint Kitts and Nevis (Saint Kitts and Nevis)", flag: "KN" },
    { value: "LC", label: "Saint Lucia (Saint Lucia)", flag: "LC" },
    { value: "VC", label: "Saint Vincent and the Grenadines (Saint Vincent and the Grenadines)", flag: "VC" },
    { value: "WS", label: "Samoa (Samoa)", flag: "WS" },
    { value: "SM", label: "San Marino (San Marino)", flag: "SM" },
    { value: "ST", label: "São Tomé and Príncipe (São Tomé and Príncipe)", flag: "ST" },
    { value: "SA", label: "Saudi Arabia (المملكة العربية السعودية)", flag: "SA" },
    { value: "SN", label: "Senegal (Sénégal)", flag: "SN" },
    { value: "RS", label: "Serbia (Србија)", flag: "RS" },
    { value: "SC", label: "Seychelles (Seychelles)", flag: "SC" },
    { value: "SL", label: "Sierra Leone (Sierra Leone)", flag: "SL" },
    { value: "SG", label: "Singapore (新加坡)", flag: "SG" },
    { value: "SK", label: "Slovakia (Slovensko)", flag: "SK" },
    { value: "SI", label: "Slovenia (Slovenija)", flag: "SI" },
    { value: "SB", label: "Solomon Islands (Solomon Islands)", flag: "SB" },
    { value: "SO", label: "Somalia (Soomaaliya)", flag: "SO" },
    { value: "ZA", label: "South Africa (South Africa)", flag: "ZA" },
    { value: "ES", label: "Spain (España)", flag: "ES" },
    { value: "LK", label: "Sri Lanka (ශ්‍රී ලංකාව)", flag: "LK" },
    { value: "SD", label: "Sudan (السودان)", flag: "SD" },
    { value: "SR", label: "Suriname (Suriname)", flag: "SR" },
    { value: "SZ", label: "Eswatini (Swaziland)", flag: "SZ" },
    { value: "SE", label: "Sweden (Sverige)", flag: "SE" },
    { value: "CH", label: "Switzerland (Schweiz)", flag: "CH" },
    { value: "SY", label: "Syria (سوريا)", flag: "SY" },
    { value: "TW", label: "Taiwan (台灣)", flag: "TW" },
    { value: "TJ", label: "Tajikistan (Тоҷикистон)", flag: "TJ" },
    { value: "TZ", label: "Tanzania (Tanzania)", flag: "TZ" },
    { value: "TH", label: "Thailand (ประเทศไทย)", flag: "TH" },
    { value: "TL", label: "Timor-Leste (Timor-Leste)", flag: "TL" },
    { value: "TG", label: "Togo (Togo)", flag: "TG" },
    { value: "TO", label: "Tonga (Tonga)", flag: "TO" },
    { value: "TT", label: "Trinidad and Tobago (Trinidad and Tobago)", flag: "TT" },
    { value: "TN", label: "Tunisia (تونس)", flag: "TN" },
    { value: "TR", label: "Turkey (Türkiye)", flag: "TR" },
    { value: "TM", label: "Turkmenistan (Türkmenistan)", flag: "TM" },
    { value: "TV", label: "Tuvalu (Tuvalu)", flag: "TV" },
    { value: "UG", label: "Uganda (Uganda)", flag: "UG" },
    { value: "UA", label: "Ukraine (Україна)", flag: "UA" },
    { value: "AE", label: "United Arab Emirates (الإمارات)", flag: "AE" },
    { value: "GB", label: "United Kingdom (United Kingdom)", flag: "GB" },
    { value: "US", label: "United States (United States)", flag: "US" },
    { value: "UY", label: "Uruguay (Uruguay)", flag: "UY" },
    { value: "UZ", label: "Uzbekistan (Oʻzbekiston)", flag: "UZ" },
    { value: "VU", label: "Vanuatu (Vanuatu)", flag: "VU" },
    { value: "VE", label: "Venezuela (Venezuela)", flag: "VE" },
    { value: "VN", label: "Vietnam (Việt Nam)", flag: "VN" },
    { value: "YE", label: "Yemen (اليمن)", flag: "YE" },
    { value: "ZM", label: "Zambia (Zambia)", flag: "ZM" },
    { value: "ZW", label: "Zimbabwe (Zimbabwe)", flag: "ZW" },
];
